from typing import TypedDict

class JSONResult(TypedDict):
    DT_RowId: str
    ftp: str
    friend: int
    pt: str
    label: str
    zid: str
    pos: int
    position_in_cat: int
    name: str
    cp: int
    zwid: int
    res_id: str
    lag: int
    uid: str
    time: list[float]
    time_gun: float
    gap: int
    vtta: str
    vttat: int
    male: int
    tid: str
    topen: str
    tname: str
    tc: str
    tbc: str
    tbd: str
    zeff: int
    category: str
    height: list[float]
    flag: str
    avg_hr: list[int]
    max_hr: list[int]
    hrmax: list[int]
    hrm: int
    weight: list[float]
    power_type: int
    display_pos: int
    src: int
    age: str
    zada: int
    note: str
    div: int
    divw: int
    skill: str
    skill_b: str
    skill_gain: str
    np: list[int]
    hrr: list[float]
    hreff: list[str]
    avg_power: list[int]
    avg_wkg: list[str]
    wkg_ftp: list[str]
    wftp: list[int]
    wkg_guess: int
    wkg1200: list[str]
    wkg300: list[str]
    wkg120: list[str]
    wkg60: list[str]
    wkg30: list[str]
    wkg15: list[str]
    wkg5: list[str]
    w1200: list[str]
    w300: list[str]
    w120: list[str]
    w60: list[str]
    w30: list[str]
    w15: list[str]
    w5: list[str]
    is_guess: int
    upg: int
    penalty: str
    reg: int
    fl: str
    pts: str
    pts_pos: str
    info: int
    info_notes: list[str]
